---
- name: add EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: update all yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install tools
  yum:
    name: "{{ item }}"
  with_items:
    - curl-devel
    - git
    - mod_ssl
    - openssl-devel
    - python34-devel
