---
- name: update WordPress URLs
  no_log: True
  command: mysql -u wordpress --password={{ wp_db_pass }} wordpress \
           -e "update wp_options set option_value = \"https://www.{{ ansible_ssh_host }}\" where option_name = '{{ item }}';"
  with_items:
    - "siteurl"
    - "home"
