---
- command: date '+%Y-%m-%d-%H%M%S'
  register: date

- name: dump WordPress database
  shell: mysqldump wordpress > /home/{{ deploy_user }}/backups/db/export-{{ date.stdout }}.sql

- name: compress database dump
  command: xz -f /home/{{ deploy_user }}/backups/db/export-{{ date.stdout }}.sql

- name: download database dump
  fetch:
    src: /home/{{ deploy_user }}/backups/db/export-{{ date.stdout }}.sql.xz
    dest: "{{ lookup('env', 'PWD') }}"
    fail_on_missing: yes
