---
- name: Set up WordPress on a CentOS VM
  remote_user: root
  hosts: all

  vars_files:
    - base.yml
    - session.yml

  roles:
    - { role: users }
    - { role: database }
    - { role: server }
    - { role: wordpress }
    # It's important this comes after the WordPress role since it
    # modifies the wp_options database table
    - { role: tls, when: with_tls != "" }
    - { role: cleanup }
    - { role: security }
