---
- name: Set up WordPress on a CentOS VM
  remote_user: root
  hosts: all

  vars_files:
    - session.yml

  vars:
    project_dir: /var/www/html

    # After setup, root SSH access will be removed
    deploy_user: deploy
    deploy_group: apache
    become_user: deploy

  roles:
    - { role: users }
    - { role: database }
    - { role: server }
    - { role: wordpress }
    # It's important this comes after the WordPress role since it
    # modifies the wp_options database table
    - { role: tls, when: with_tls != "" }
    - { role: cleanup }
    - { role: security }
