---
- name: Set up WordPress on a DigitalOcean CentOS VM
  remote_user: root
  hosts: all

  vars:
    hostname: "{{ lookup('env', 'SERVER') }}"
    keyfile: "{{ lookup('env', 'IDENTITY') }}.pub"

    # After setup, root SSH access will be removed
    deploy_user: deploy
    deploy_group: "{{ deploy_user }}"

    root_db_pass: "{{ lookup('env', 'ROOT_DB_PASS') }}"
    wp_db_pass: "{{ lookup('env', 'WP_DB_PASS') }}"

    wp_admin_pass: "{{ lookup('env', 'WP_ADMIN_PASS') }}"
    admin_email: "{{ lookup('env', 'EMAIL') }}"
  roles:
    - { role: tools }
    - { role: users }
    - { role: database }
    - { role: apache }
    - { role: wp }
    - { role: cleanup }
