---
- name: Set up WordPress on a CentOS VM
  remote_user: root
  hosts: all

  vars_files:
    - session.yml

  vars:
    project_dir: /var/www/html

    # After setup, root SSH access will be removed
    deploy_user: deploy
    deploy_group: apache
    become_user: deploy

  roles:
    - { role: prereqs }
    - { role: database }
    - { role: apache }
    - { role: wordpress, become: true, become_user: "{{ deploy_user }}" }
    - { role: cleanup }
    - { role: security }
