---
- name: Set up WordPress on a DigitalOcean CentOS VM
  remote_user: root
  hosts: all

  vars:
    hostname: "{{ lookup('env', 'SERVER') }}"

    # After setup, root SSH access will be removed
    deploy_user: deploy
    deploy_group: "{{ deploy_user }}"

    root_db_pass: "{{ lookup('env', 'ROOT_DB_PASS') }}"
    wp_db_pass: "{{ lookup('env', 'WP_DB_PASS') }}"

    import_db: "{{ lookup('env', 'IMPORT_DB') }}"

  roles:
    - { role: tools }
    - { role: users }
    - { role: database }
    - { role: apache }
    - { role: wp }
    - { role: cleanup }
