---
- name: Add a TLS certificate
  remote_user: deploy
  hosts: all

  vars_files:
    - base.yml

  vars_prompt:
    - name: wp_db_pass
      private: yes
      prompt: password for MariaDB wordpress user

  roles:
    - role: tls
