---
- name: restart fail2ban
  service: name=fail2ban state=restarted enabled=yes

# xml-rpc attacks are when someone repeatedly tries to login to your
# WordPress instance; by default there's no limit to how many times in
# a row they can do this, so it functions as a denial-of-service
# attack
- name: install xml-rpc fail2ban filter
  copy:
    src: apache-xmlrpc.filter
    dest: /etc/fail2ban/filter.d/apache-xmlrpc.conf
    mode: 664
    owner: apache
    group: apache

- name: install xml-rpc fail2ban jail
  copy:
    src: apache-xmlrpc.jail
    dest: /etc/fail2ban/jail.local
    mode: 664
    owner: apache
    group: apache
