---
- name: install wp-cli
  get_url:
    checksum: sha512:{{ CLI_SHA }}
    dest: /usr/local/bin/wp-cli
    group: "{{ deploy_group }}"
    mode: 0755
    owner: "{{ deploy_user }}"
    url: https://github.com/wp-cli/wp-cli/releases/download/v{{ CLI_VER }}/wp-cli-{{ CLI_VER }}.phar
