---
- name: start MariaDB
  service:
    name: mariadb
    state: restarted
    enabled: yes

- name: check for existing MariaDB configuration
  stat:
    path: /etc/my.cnf.d/wp.cnf
  register: my_cnf

- name: set MariaDB root password
  mysql_user:
    name: root
    password: "{{ root_db_pass }}"
  when: my_cnf.stat.exists == False

- name: create MariaDB configuration
  template:
    src: wp.cnf.j2
    dest: /etc/my.cnf.d/wp.cnf
    mode: 0644
    owner: mysql
    group: mysql

- name: disable remote root login
  no_log: True
  command: mysql -u root --password={{ root_db_pass }} -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"

# This task and the next two are the same ones performed when you run
# `mysql_secure_installation`
- name: remove anonymous roles
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_password: "{{ root_db_pass }}"

- name: remove test database
  mysql_db:
    name: test
    state: absent
    login_password: "{{ root_db_pass }}"
    login_user: root

- name: flush privileges
  no_log: True
  command: mysql -u root --password={{ root_db_pass }} -e "FLUSH PRIVILEGES;"

- name: create wordpress database
  mysql_db:
    name: wordpress
    state: present
    login_password: "{{ root_db_pass }}"
    login_user: root

- name: create wordpress role
  mysql_user:
    name: wordpress
    password: "{{ wp_db_pass }}"
    priv: "wordpress.*:ALL"
    state: present
    login_password: "{{ root_db_pass }}"
    login_user: root
    update_password: on_create

- name: create MariaDB log directory
  file:
    path: /var/log/mysql
    owner: mysql
    group: mysql
    state: directory
