---
- name: add MariaDB repo
  copy:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo

- name: add EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: update all yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install tools
  yum:
    name: "{{ item }}"
  with_items:
    - MariaDB-client
    - MariaDB-server
    - MySQL-python
    # for acme-tiny
    - python34-devel
    # for backups
    - xz
