---
- name: add MariaDB repo
  copy:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo

- name: add EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: update all yum packages
  yum:
    name: '*'
    state: latest

- name: install tools
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - MariaDB-client
    - MariaDB-server
    - MySQL-python
    - python34-devel
    # for backups
    - xz
