---
- name: create apache user
  user:
    name: apache
    group: "{{ deploy_group }}"

- name: create project directories
  file:
    group: "{{ deploy_group }}"
    mode: 2755
    owner: "{{ deploy_user }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ project_dir }}"

# Including our own, to make re-tries easier
- name: remove Apache configurations
  file:
    path: /etc/httpd/conf.d/{{ item }}.conf
    state: absent
  with_items:
    - ssl
    - userdir
    - welcome
    - wp

- name: configure virtual host
  template:
    src: wp.conf.j2
    dest: /etc/httpd/conf.d/wp.conf

- name: restart Apache
  systemd:
    enabled: yes
    name: httpd
    state: restarted
