---
- name: add EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: add IUS repo
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: update all yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install tools
  yum:
    name: "{{ item }}"
  with_items:
    - httpd-devel
    - mod_php
    - php71u-common
    - php71u-devel
    - php71u-mysqlnd
    - php71u-opcache
    - php71u-xmlrpc
    - sendmail
